/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkspaceRouteImport } from './routes/workspace'
import { Route as StackIntelligenceRouteImport } from './routes/stack-intelligence'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RevivalBoardRouteImport } from './routes/revival-board'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as NewDraftRouteImport } from './routes/new-draft'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InsightsLabRouteImport } from './routes/insights-lab'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as IdeaReviewRouteImport } from './routes/idea-review'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AiAssistantRouteImport } from './routes/ai-assistant'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectSlugRouteImport } from './routes/project.$slug'

const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const StackIntelligenceRoute = StackIntelligenceRouteImport.update({
  id: '/stack-intelligence',
  path: '/stack-intelligence',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RevivalBoardRoute = RevivalBoardRouteImport.update({
  id: '/revival-board',
  path: '/revival-board',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const NewDraftRoute = NewDraftRouteImport.update({
  id: '/new-draft',
  path: '/new-draft',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsLabRoute = InsightsLabRouteImport.update({
  id: '/insights-lab',
  path: '/insights-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const IdeaReviewRoute = IdeaReviewRouteImport.update({
  id: '/idea-review',
  path: '/idea-review',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AiAssistantRoute = AiAssistantRouteImport.update({
  id: '/ai-assistant',
  path: '/ai-assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectSlugRoute = ProjectSlugRouteImport.update({
  id: '/project/$slug',
  path: '/project/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-assistant': typeof AiAssistantRoute
  '/dashboard': typeof DashboardRoute
  '/feed': typeof FeedRoute
  '/idea-review': typeof IdeaReviewRoute
  '/insights': typeof InsightsRoute
  '/insights-lab': typeof InsightsLabRoute
  '/login': typeof LoginRoute
  '/new-draft': typeof NewDraftRoute
  '/profile': typeof ProfileRoute
  '/revival-board': typeof RevivalBoardRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/stack-intelligence': typeof StackIntelligenceRoute
  '/workspace': typeof WorkspaceRoute
  '/project/$slug': typeof ProjectSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-assistant': typeof AiAssistantRoute
  '/dashboard': typeof DashboardRoute
  '/feed': typeof FeedRoute
  '/idea-review': typeof IdeaReviewRoute
  '/insights': typeof InsightsRoute
  '/insights-lab': typeof InsightsLabRoute
  '/login': typeof LoginRoute
  '/new-draft': typeof NewDraftRoute
  '/profile': typeof ProfileRoute
  '/revival-board': typeof RevivalBoardRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/stack-intelligence': typeof StackIntelligenceRoute
  '/workspace': typeof WorkspaceRoute
  '/project/$slug': typeof ProjectSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-assistant': typeof AiAssistantRoute
  '/dashboard': typeof DashboardRoute
  '/feed': typeof FeedRoute
  '/idea-review': typeof IdeaReviewRoute
  '/insights': typeof InsightsRoute
  '/insights-lab': typeof InsightsLabRoute
  '/login': typeof LoginRoute
  '/new-draft': typeof NewDraftRoute
  '/profile': typeof ProfileRoute
  '/revival-board': typeof RevivalBoardRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/stack-intelligence': typeof StackIntelligenceRoute
  '/workspace': typeof WorkspaceRoute
  '/project/$slug': typeof ProjectSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-assistant'
    | '/dashboard'
    | '/feed'
    | '/idea-review'
    | '/insights'
    | '/insights-lab'
    | '/login'
    | '/new-draft'
    | '/profile'
    | '/revival-board'
    | '/settings'
    | '/signup'
    | '/stack-intelligence'
    | '/workspace'
    | '/project/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-assistant'
    | '/dashboard'
    | '/feed'
    | '/idea-review'
    | '/insights'
    | '/insights-lab'
    | '/login'
    | '/new-draft'
    | '/profile'
    | '/revival-board'
    | '/settings'
    | '/signup'
    | '/stack-intelligence'
    | '/workspace'
    | '/project/$slug'
  id:
    | '__root__'
    | '/'
    | '/ai-assistant'
    | '/dashboard'
    | '/feed'
    | '/idea-review'
    | '/insights'
    | '/insights-lab'
    | '/login'
    | '/new-draft'
    | '/profile'
    | '/revival-board'
    | '/settings'
    | '/signup'
    | '/stack-intelligence'
    | '/workspace'
    | '/project/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiAssistantRoute: typeof AiAssistantRoute
  DashboardRoute: typeof DashboardRoute
  FeedRoute: typeof FeedRoute
  IdeaReviewRoute: typeof IdeaReviewRoute
  InsightsRoute: typeof InsightsRoute
  InsightsLabRoute: typeof InsightsLabRoute
  LoginRoute: typeof LoginRoute
  NewDraftRoute: typeof NewDraftRoute
  ProfileRoute: typeof ProfileRoute
  RevivalBoardRoute: typeof RevivalBoardRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  StackIntelligenceRoute: typeof StackIntelligenceRoute
  WorkspaceRoute: typeof WorkspaceRoute
  ProjectSlugRoute: typeof ProjectSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workspace': {
      id: '/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stack-intelligence': {
      id: '/stack-intelligence'
      path: '/stack-intelligence'
      fullPath: '/stack-intelligence'
      preLoaderRoute: typeof StackIntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/revival-board': {
      id: '/revival-board'
      path: '/revival-board'
      fullPath: '/revival-board'
      preLoaderRoute: typeof RevivalBoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-draft': {
      id: '/new-draft'
      path: '/new-draft'
      fullPath: '/new-draft'
      preLoaderRoute: typeof NewDraftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights-lab': {
      id: '/insights-lab'
      path: '/insights-lab'
      fullPath: '/insights-lab'
      preLoaderRoute: typeof InsightsLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/idea-review': {
      id: '/idea-review'
      path: '/idea-review'
      fullPath: '/idea-review'
      preLoaderRoute: typeof IdeaReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-assistant': {
      id: '/ai-assistant'
      path: '/ai-assistant'
      fullPath: '/ai-assistant'
      preLoaderRoute: typeof AiAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/$slug': {
      id: '/project/$slug'
      path: '/project/$slug'
      fullPath: '/project/$slug'
      preLoaderRoute: typeof ProjectSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiAssistantRoute: AiAssistantRoute,
  DashboardRoute: DashboardRoute,
  FeedRoute: FeedRoute,
  IdeaReviewRoute: IdeaReviewRoute,
  InsightsRoute: InsightsRoute,
  InsightsLabRoute: InsightsLabRoute,
  LoginRoute: LoginRoute,
  NewDraftRoute: NewDraftRoute,
  ProfileRoute: ProfileRoute,
  RevivalBoardRoute: RevivalBoardRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  StackIntelligenceRoute: StackIntelligenceRoute,
  WorkspaceRoute: WorkspaceRoute,
  ProjectSlugRoute: ProjectSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
