const mongoose = require("mongoose");
const dotenv = require("dotenv");
const dns = require("node:dns");
const Burial = require("./models/burial");

dotenv.config();

dns.setServers(["1.1.1.1", "8.8.8.8"]);
dns.setDefaultResultOrder("ipv4first");

const fakeBurials = [
  {
    projectName: "StudyBuddy",
    oneLiner: "AI-powered study planner for college students",
    domain: "web",
    techStack: ["React", "Node.js", "MongoDB"],
    teamSize: "2-3",
    stageDied: "50% done",
    whyItDied: "We kept adding features and never actually finished the core product. Scope creep killed us.",
    timeSpent: { value: 2, unit: "months" },
    salvageable: "The calendar UI component is reusable",
    openForRevival: true,
    isAnonymous: false,
  },
  {
    projectName: "GigMap",
    oneLiner: "Freelance gig finder with map-based search",
    domain: "web",
    techStack: ["Vue.js", "Django", "PostgreSQL"],
    teamSize: "solo",
    stageDied: "Prototype",
    whyItDied: "Got a job offer and stopped working on it. Never came back.",
    timeSpent: { value: 3, unit: "weeks" },
    salvageable: "Django REST API backend is solid",
    openForRevival: true,
    isAnonymous: false,
  },
  {
    projectName: "SnapRecipe",
    oneLiner: "Take a photo of ingredients and get recipe suggestions",
    domain: "mobile",
    techStack: ["Flutter", "Firebase", "Python"],
    teamSize: "2-3",
    stageDied: "Almost complete",
    whyItDied: "The ML model accuracy was only 60% and we couldn't improve it before the deadline.",
    timeSpent: { value: 3, unit: "months" },
    salvageable: "Flutter UI is complete and polished",
    openForRevival: false,
    isAnonymous: false,
  },
  {
    projectName: "DevDuel",
    oneLiner: "Real-time coding battles between developers",
    domain: "web",
    techStack: ["React", "Socket.io", "Node.js", "MongoDB"],
    teamSize: "4+",
    stageDied: "50% done",
    whyItDied: "Team of 5 people, 3 stopped showing up after week 2. Couldn't continue alone.",
    timeSpent: { value: 6, unit: "weeks" },
    salvageable: "Socket.io real-time code editor works well",
    openForRevival: true,
    isAnonymous: false,
  },
  {
    projectName: "MoodBoard AI",
    oneLiner: "Generate design moodboards from a text prompt",
    domain: "ml",
    techStack: ["Python", "Stable Diffusion", "FastAPI"],
    teamSize: "solo",
    stageDied: "Prototype",
    whyItDied: "GPU costs were too high to run inference. Couldn't afford cloud bills as a student.",
    timeSpent: { value: 1, unit: "months" },
    salvageable: "FastAPI wrapper around Stable Diffusion is reusable",
    openForRevival: false,
    isAnonymous: true,
  },
  {
    projectName: "CampusEats",
    oneLiner: "Food delivery app for college campuses",
    domain: "mobile",
    techStack: ["React Native", "Node.js", "MongoDB"],
    teamSize: "4+",
    stageDied: "Launched but abandoned",
    whyItDied: "Launched on campus but couldn't get restaurants to onboard. No supply side.",
    timeSpent: { value: 4, unit: "months" },
    salvageable: "Full delivery tracking UI and driver app",
    openForRevival: true,
    isAnonymous: false,
  },
  {
    projectName: "HabitChain",
    oneLiner: "Habit tracker with blockchain-based accountability",
    domain: "web",
    techStack: ["React", "Solidity", "Ethereum"],
    teamSize: "2-3",
    stageDied: "Idea only",
    whyItDied: "Spent 3 weeks researching blockchain and never wrote a single line of product code.",
    timeSpent: { value: 3, unit: "weeks" },
    salvageable: "Nothing, we only have a Figma file",
    openForRevival: false,
    isAnonymous: true,
  },
  {
    projectName: "PeerReview",
    oneLiner: "Anonymous peer code review platform for students",
    domain: "web",
    techStack: ["Next.js", "Supabase", "TypeScript"],
    teamSize: "solo",
    stageDied: "50% done",
    whyItDied: "Exams hit and I kept telling myself I'd get back to it after. Never did.",
    timeSpent: { value: 5, unit: "weeks" },
    salvageable: "Auth system and code diff viewer component",
    openForRevival: true,
    isAnonymous: false,
  },
  {
    projectName: "LocalLingo",
    oneLiner: "Language exchange app connecting locals with travelers",
    domain: "mobile",
    techStack: ["Flutter", "Firebase"],
    teamSize: "2-3",
    stageDied: "Almost complete",
    whyItDied: "Pivoted the idea 4 times. Started as translation app, became language exchange, then tutoring. Lost focus completely.",
    timeSpent: { value: 2, unit: "months" },
    salvageable: "Firebase auth and chat module",
    openForRevival: false,
    isAnonymous: false,
  },
  {
    projectName: "ResumeRadar",
    oneLiner: "ATS resume scanner with improvement suggestions",
    domain: "web",
    techStack: ["React", "Python", "spaCy", "FastAPI"],
    teamSize: "solo",
    stageDied: "Almost complete",
    whyItDied: "Found 5 existing tools doing the same thing better. Killed motivation instantly.",
    timeSpent: { value: 6, unit: "weeks" },
    salvageable: "spaCy NLP pipeline for resume parsing",
    openForRevival: true,
    isAnonymous: false,
  },
  {
    projectName: "SplitIt",
    oneLiner: "Expense splitting app for roommates",
    domain: "mobile",
    techStack: ["React Native", "Firebase"],
    teamSize: "2-3",
    stageDied: "Launched but abandoned",
    whyItDied: "Built it, used it ourselves for a month, then switched to Splitwise. Couldn't compete.",
    timeSpent: { value: 2, unit: "months" },
    salvageable: "The whole app actually works, just no users",
    openForRevival: false,
    isAnonymous: false,
  },
  {
    projectName: "CodeMentor Bot",
    oneLiner: "Slack bot that reviews code and suggests improvements",
    domain: "web",
    techStack: ["Node.js", "OpenAI API", "Slack API"],
    teamSize: "solo",
    stageDied: "Prototype",
    whyItDied: "OpenAI API costs scaled faster than expected. $200 bill in first week of beta testing.",
    timeSpent: { value: 2, unit: "weeks" },
    salvageable: "Slack bot boilerplate and OpenAI integration",
    openForRevival: true,
    isAnonymous: true,
  },
  {
    projectName: "GreenRoute",
    oneLiner: "Navigation app that shows the most eco-friendly route",
    domain: "mobile",
    techStack: ["Flutter", "Google Maps API", "Python"],
    teamSize: "4+",
    stageDied: "50% done",
    whyItDied: "Submitted for a hackathon, didn't win, team lost interest immediately after.",
    timeSpent: { value: 3, unit: "weeks" },
    salvageable: "Flutter Google Maps integration",
    openForRevival: true,
    isAnonymous: false,
  },
  {
    projectName: "NightOwl",
    oneLiner: "Late night study session finder for college campuses",
    domain: "web",
    techStack: ["React", "Node.js", "Socket.io", "MongoDB"],
    teamSize: "solo",
    stageDied: "Idea only",
    whyItDied: "Realized I was building this instead of actually studying for my own exams.",
    timeSpent: { value: 4, unit: "days" },
    salvageable: "Nothing yet",
    openForRevival: false,
    isAnonymous: true,
  },
  {
    projectName: "DocuSign Clone",
    oneLiner: "Free e-signature platform for small businesses",
    domain: "web",
    techStack: ["React", "Django", "PostgreSQL", "AWS S3"],
    teamSize: "2-3",
    stageDied: "Almost complete",
    whyItDied: "Legal concerns about digital signature validity in India. Got scared and stopped.",
    timeSpent: { value: 3, unit: "months" },
    salvageable: "PDF annotation and signature canvas component",
    openForRevival: true,
    isAnonymous: false,
  },
  {
    projectName: "TutorLink",
    oneLiner: "Peer tutoring marketplace for university students",
    domain: "web",
    techStack: ["Next.js", "Node.js", "MongoDB", "Stripe"],
    teamSize: "4+",
    stageDied: "50% done",
    whyItDied: "Payment integration was hard, team got frustrated, everyone slowly stopped committing.",
    timeSpent: { value: 2, unit: "months" },
    salvageable: "Matching algorithm and booking system",
    openForRevival: true,
    isAnonymous: false,
  },
  {
    projectName: "PixelPet",
    oneLiner: "Virtual pet game that reacts to your daily step count",
    domain: "mobile",
    techStack: ["Flutter", "Firebase", "HealthKit"],
    teamSize: "solo",
    stageDied: "Prototype",
    whyItDied: "Got distracted by a new idea about AR pets. Classic shiny object syndrome.",
    timeSpent: { value: 3, unit: "weeks" },
    salvageable: "Step count integration with HealthKit",
    openForRevival: false,
    isAnonymous: false,
  },
  {
    projectName: "Stackwise",
    oneLiner: "Tech stack recommender for new projects",
    domain: "web",
    techStack: ["React", "Python", "scikit-learn", "FastAPI"],
    teamSize: "solo",
    stageDied: "Almost complete",
    whyItDied: "Couldn't figure out how to deploy the ML model cheaply. Heroku free tier died.",
    timeSpent: { value: 5, unit: "weeks" },
    salvageable: "scikit-learn recommendation model and training data",
    openForRevival: true,
    isAnonymous: false,
  },
  {
    projectName: "EventHive",
    oneLiner: "College event discovery and RSVP platform",
    domain: "web",
    techStack: ["React", "Node.js", "MongoDB"],
    teamSize: "4+",
    stageDied: "Launched but abandoned",
    whyItDied: "Launched in college, got 200 users, then college admin blocked promotion emails. Growth died.",
    timeSpent: { value: 3, unit: "months" },
    salvageable: "Full working app, just needs a new distribution channel",
    openForRevival: true,
    isAnonymous: false,
  },
  {
    projectName: "SleepSync",
    oneLiner: "Sleep tracker that syncs schedules between roommates",
    domain: "mobile",
    techStack: ["React Native", "Firebase"],
    teamSize: "2-3",
    stageDied: "Idea only",
    whyItDied: "We spent 2 weeks arguing about which database to use and never started coding.",
    timeSpent: { value: 2, unit: "weeks" },
    salvageable: "A very detailed Notion document",
    openForRevival: false,
    isAnonymous: true,
  },
  {
    projectName: "JobTrail",
    oneLiner: "Track all your job applications in one place",
    domain: "web",
    techStack: ["React", "Supabase"],
    teamSize: "solo",
    stageDied: "Almost complete",
    whyItDied: "Got a job. Didn't need it anymore. Ironic.",
    timeSpent: { value: 4, unit: "weeks" },
    salvageable: "Entire frontend, fully functional",
    openForRevival: true,
    isAnonymous: false,
  },
  {
    projectName: "QuizCraft",
    oneLiner: "Auto-generate quizzes from any YouTube video",
    domain: "ml",
    techStack: ["Python", "OpenAI API", "React", "FastAPI"],
    teamSize: "2-3",
    stageDied: "50% done",
    whyItDied: "YouTube transcript API got rate limited. Whole pipeline broke and we gave up.",
    timeSpent: { value: 6, unit: "weeks" },
    salvageable: "Quiz generation prompt and React quiz UI",
    openForRevival: true,
    isAnonymous: false,
  },
  {
    projectName: "Wandr",
    oneLiner: "Solo travel companion app with offline maps",
    domain: "mobile",
    techStack: ["Flutter", "OpenStreetMap", "SQLite"],
    teamSize: "solo",
    stageDied: "Prototype",
    whyItDied: "Offline map storage was eating 2GB on device. Couldn't solve it with my skills at the time.",
    timeSpent: { value: 1, unit: "months" },
    salvageable: "OpenStreetMap Flutter integration",
    openForRevival: false,
    isAnonymous: false,
  },
  {
    projectName: "ClassVault",
    oneLiner: "Shared note repository for university courses",
    domain: "web",
    techStack: ["React", "Django", "PostgreSQL", "AWS S3"],
    teamSize: "4+",
    stageDied: "Launched but abandoned",
    whyItDied: "Copyright concerns — professors complained their material was being shared without permission.",
    timeSpent: { value: 4, unit: "months" },
    salvageable: "S3 file upload system and search feature",
    openForRevival: false,
    isAnonymous: true,
  },
  {
    projectName: "FocusForge",
    oneLiner: "Pomodoro timer with distraction website blocker",
    domain: "web",
    techStack: ["React", "Chrome Extension API", "Node.js"],
    teamSize: "solo",
    stageDied: "Almost complete",
    whyItDied: "Chrome extension review process took 3 weeks. Lost momentum waiting.",
    timeSpent: { value: 5, unit: "weeks" },
    salvageable: "Chrome extension boilerplate and Pomodoro timer logic",
    openForRevival: true,
    isAnonymous: false,
  },
];

const seedDB = async () => {
  try {
    await mongoose.connect(process.env.MONGO_URI);
    console.log("✅ MongoDB Connected");

    await Burial.deleteMany({});
    console.log("🗑️  Cleared existing burials");

    await Burial.insertMany(fakeBurials);
    console.log(`🌱 Seeded ${fakeBurials.length} fake burials`);

    mongoose.connection.close();
    console.log("🔌 Connection closed");
  } catch (err) {
    console.error("❌ Seed error:", err);
    process.exit(1);
  }
};

seedDB();