const mongoose = require("mongoose");
const dotenv = require("dotenv");
const dns = require("node:dns");
const Draft = require("./models/draft");

dotenv.config();

dns.setServers(["1.1.1.1", "8.8.8.8"]);
dns.setDefaultResultOrder("ipv4first");

const fakeBurials = [
  {
    projectName: "StudyBuddy",
    oneLiner: "AI-powered study planner for college students",
    domain: "web",
    techStack: ["React", "Node.js", "MongoDB"],
    teamSize: "2-3",
    currentStage: "50% done",
    failureReason: "We kept adding features and never actually finished the core product. Scope creep killed us.",
    timeSpent: { value: 2, unit: "months" },
    isAnonymous: false,
  },
  {
    projectName: "GigMap",
    oneLiner: "Freelance gig finder with map-based search",
    domain: "web",
    techStack: ["Vue.js", "Django", "PostgreSQL"],
    teamSize: "solo",
    currentStage: "Prototype",
    failureReason: "Got a job offer and stopped working on it. Never came back.",
    timeSpent: { value: 3, unit: "weeks" },
    isAnonymous: false,
  },
  {
    projectName: "SnapRecipe",
    oneLiner: "Take a photo of ingredients and get recipe suggestions",
    domain: "mobile",
    techStack: ["Flutter", "Firebase", "Python"],
    teamSize: "2-3",
    currentStage: "Almost complete",
    failureReason: "The ML model accuracy was only 60% and we couldn't improve it before the deadline.",
    timeSpent: { value: 3, unit: "months" },
    isAnonymous: false,
  },
  {
    projectName: "DevDuel",
    oneLiner: "Real-time coding battles between developers",
    domain: "web",
    techStack: ["React", "Socket.io", "Node.js", "MongoDB"],
    teamSize: "4+",
    currentStage: "50% done",
    failureReason: "Team of 5 people, 3 stopped showing up after week 2. Couldn't continue alone.",
    timeSpent: { value: 6, unit: "weeks" },
    isAnonymous: false,
  },
  {
    projectName: "MoodBoard AI",
    oneLiner: "Generate design moodboards from a text prompt",
    domain: "ml",
    techStack: ["Python", "Stable Diffusion", "FastAPI"],
    teamSize: "solo",
    currentStage: "Prototype",
    failureReason: "GPU costs were too high to run inference. Couldn't afford cloud bills as a student.",
    timeSpent: { value: 1, unit: "months" },
    isAnonymous: true,
  },
  {
    projectName: "CampusEats",
    oneLiner: "Food delivery app for college campuses",
    domain: "mobile",
    techStack: ["React Native", "Node.js", "MongoDB"],
    teamSize: "4+",
    currentStage: "Launched but abandoned",
    failureReason: "Launched on campus but couldn't get restaurants to onboard. No supply side.",
    timeSpent: { value: 4, unit: "months" },
    isAnonymous: false,
  },
  {
    projectName: "HabitChain",
    oneLiner: "Habit tracker with blockchain-based accountability",
    domain: "web",
    techStack: ["React", "Solidity", "Ethereum"],
    teamSize: "2-3",
    currentStage: "Idea only",
    failureReason: "Spent 3 weeks researching blockchain and never wrote a single line of product code.",
    timeSpent: { value: 3, unit: "weeks" },
    isAnonymous: true,
  },
  {
    projectName: "PeerReview",
    oneLiner: "Anonymous peer code review platform for students",
    domain: "web",
    techStack: ["Next.js", "Supabase", "TypeScript"],
    teamSize: "solo",
    currentStage: "50% done",
    failureReason: "Exams hit and I kept telling myself I'd get back to it after. Never did.",
    timeSpent: { value: 5, unit: "weeks" },
    isAnonymous: false,
  },
  {
    projectName: "LocalLingo",
    oneLiner: "Language exchange app connecting locals with travelers",
    domain: "mobile",
    techStack: ["Flutter", "Firebase"],
    teamSize: "2-3",
    currentStage: "Almost complete",
    failureReason: "Pivoted the idea 4 times. Started as translation app, became language exchange, then tutoring. Lost focus completely.",
    timeSpent: { value: 2, unit: "months" },
    isAnonymous: false,
  },
  {
    projectName: "ResumeRadar",
    oneLiner: "ATS resume scanner with improvement suggestions",
    domain: "web",
    techStack: ["React", "Python", "spaCy", "FastAPI"],
    teamSize: "solo",
    currentStage: "Almost complete",
    failureReason: "Found 5 existing tools doing the same thing better. Killed motivation instantly.",
    timeSpent: { value: 6, unit: "weeks" },
    isAnonymous: false,
  },
  {
    projectName: "SplitIt",
    oneLiner: "Expense splitting app for roommates",
    domain: "mobile",
    techStack: ["React Native", "Firebase"],
    teamSize: "2-3",
    currentStage: "Launched but abandoned",
    failureReason: "Built it, used it ourselves for a month, then switched to Splitwise. Couldn't compete.",
    timeSpent: { value: 2, unit: "months" },
    isAnonymous: false,
  },
  {
    projectName: "CodeMentor Bot",
    oneLiner: "Slack bot that reviews code and suggests improvements",
    domain: "web",
    techStack: ["Node.js", "OpenAI API", "Slack API"],
    teamSize: "solo",
    currentStage: "Prototype",
    failureReason: "OpenAI API costs scaled faster than expected. $200 bill in first week of beta testing.",
    timeSpent: { value: 2, unit: "weeks" },
    isAnonymous: true,
  },
  {
    projectName: "GreenRoute",
    oneLiner: "Navigation app that shows the most eco-friendly route",
    domain: "mobile",
    techStack: ["Flutter", "Google Maps API", "Python"],
    teamSize: "4+",
    currentStage: "50% done",
    failureReason: "Submitted for a hackathon, didn't win, team lost interest immediately after.",
    timeSpent: { value: 3, unit: "weeks" },
    isAnonymous: false,
  },
  {
    projectName: "NightOwl",
    oneLiner: "Late night study session finder for college campuses",
    domain: "web",
    techStack: ["React", "Node.js", "Socket.io", "MongoDB"],
    teamSize: "solo",
    currentStage: "Idea only",
    failureReason: "Realized I was building this instead of actually studying for my own exams.",
    timeSpent: { value: 4, unit: "days" },
    isAnonymous: true,
  },
  {
    projectName: "DocuSign Clone",
    oneLiner: "Free e-signature platform for small businesses",
    domain: "web",
    techStack: ["React", "Django", "PostgreSQL", "AWS S3"],
    teamSize: "2-3",
    currentStage: "Almost complete",
    failureReason: "Legal concerns about digital signature validity in India. Got scared and stopped.",
    timeSpent: { value: 3, unit: "months" },
    isAnonymous: false,
  },
  {
    projectName: "TutorLink",
    oneLiner: "Peer tutoring marketplace for university students",
    domain: "web",
    techStack: ["Next.js", "Node.js", "MongoDB", "Stripe"],
    teamSize: "4+",
    currentStage: "50% done",
    failureReason: "Payment integration was hard, team got frustrated, everyone slowly stopped committing.",
    timeSpent: { value: 2, unit: "months" },
    isAnonymous: false,
  },
  {
    projectName: "PixelPet",
    oneLiner: "Virtual pet game that reacts to your daily step count",
    domain: "mobile",
    techStack: ["Flutter", "Firebase", "HealthKit"],
    teamSize: "solo",
    currentStage: "Prototype",
    failureReason: "Got distracted by a new idea about AR pets. Classic shiny object syndrome.",
    timeSpent: { value: 3, unit: "weeks" },
    isAnonymous: false,
  },
  {
    projectName: "Stackwise",
    oneLiner: "Tech stack recommender for new projects",
    domain: "web",
    techStack: ["React", "Python", "scikit-learn", "FastAPI"],
    teamSize: "solo",
    currentStage: "Almost complete",
    failureReason: "Couldn't figure out how to deploy the ML model cheaply. Heroku free tier died.",
    timeSpent: { value: 5, unit: "weeks" },
    isAnonymous: false,
  },
  {
    projectName: "EventHive",
    oneLiner: "College event discovery and RSVP platform",
    domain: "web",
    techStack: ["React", "Node.js", "MongoDB"],
    teamSize: "4+",
    currentStage: "Launched but abandoned",
    failureReason: "Launched in college, got 200 users, then college admin blocked promotion emails. Growth died.",
    timeSpent: { value: 3, unit: "months" },
    isAnonymous: false,
  },
  {
    projectName: "SleepSync",
    oneLiner: "Sleep tracker that syncs schedules between roommates",
    domain: "mobile",
    techStack: ["React Native", "Firebase"],
    teamSize: "2-3",
    currentStage: "Idea only",
    failureReason: "We spent 2 weeks arguing about which database to use and never started coding.",
    timeSpent: { value: 2, unit: "weeks" },
    isAnonymous: true,
  },
  {
    projectName: "JobTrail",
    oneLiner: "Track all your job applications in one place",
    domain: "web",
    techStack: ["React", "Supabase"],
    teamSize: "solo",
    currentStage: "Almost complete",
    failureReason: "Got a job. Didn't need it anymore. Ironic.",
    timeSpent: { value: 4, unit: "weeks" },
    isAnonymous: false,
  },
  {
    projectName: "QuizCraft",
    oneLiner: "Auto-generate quizzes from any YouTube video",
    domain: "ml",
    techStack: ["Python", "OpenAI API", "React", "FastAPI"],
    teamSize: "2-3",
    currentStage: "50% done",
    failureReason: "YouTube transcript API got rate limited. Whole pipeline broke and we gave up.",
    timeSpent: { value: 6, unit: "weeks" },
    isAnonymous: false,
  },
  {
    projectName: "Wandr",
    oneLiner: "Solo travel companion app with offline maps",
    domain: "mobile",
    techStack: ["Flutter", "OpenStreetMap", "SQLite"],
    teamSize: "solo",
    currentStage: "Prototype",
    failureReason: "Offline map storage was eating 2GB on device. Couldn't solve it with my skills at the time.",
    timeSpent: { value: 1, unit: "months" },
    isAnonymous: false,
  },
  {
    projectName: "ClassVault",
    oneLiner: "Shared note repository for university courses",
    domain: "web",
    techStack: ["React", "Django", "PostgreSQL", "AWS S3"],
    teamSize: "4+",
    currentStage: "Launched but abandoned",
    failureReason: "Copyright concerns — professors complained their material was being shared without permission.",
    timeSpent: { value: 4, unit: "months" },
    isAnonymous: true,
  },
  {
    projectName: "FocusForge",
    oneLiner: "Pomodoro timer with distraction website blocker",
    domain: "web",
    techStack: ["React", "Chrome Extension API", "Node.js"],
    teamSize: "solo",
    currentStage: "Almost complete",
    failureReason: "Chrome extension review process took 3 weeks. Lost momentum waiting.",
    timeSpent: { value: 5, unit: "weeks" },
    isAnonymous: false,
  },
  {
    projectName: "InvoiceIt",
    oneLiner: "A small game where players compete to manage study schedules",
    domain: "game",
    techStack: ["Godot", "GDScript"],
    teamSize: "solo",
    currentStage: "Idea only",
    failureReason: "Pivoted the idea three times and lost all momentum in the process.",
    timeSpent: { value: 1, unit: "weeks" },
    isAnonymous: false,
  },
  {
    projectName: "DeployDash",
    oneLiner: "A casual game prototype about surviving as a parent",
    domain: "game",
    techStack: ["Godot", "GDScript"],
    teamSize: "2-3",
    currentStage: "Almost complete",
    failureReason: "We realized a much better version of this already existed on the App Store.",
    timeSpent: { value: 2, unit: "weeks" },
    isAnonymous: false,
  },
  {
    projectName: "ContainerCove",
    oneLiner: "A casual game prototype about surviving as a student",
    domain: "game",
    techStack: ["Phaser.js", "JavaScript"],
    teamSize: "2-3",
    currentStage: "Idea only",
    failureReason: "One teammate ghosted after week two and the rest of us couldn't keep pace.",
    timeSpent: { value: 2, unit: "days" },
    isAnonymous: true,
  },
  {
    projectName: "AttendEase",
    oneLiner: "A machine learning model that automatically sorts sleep patterns",
    domain: "ml",
    techStack: ["Python", "PyTorch", "FastAPI"],
    teamSize: "2-3",
    currentStage: "Idea only",
    failureReason: "Submitted it for a hackathon, didn't place, and interest died right after.",
    timeSpent: { value: 1, unit: "weeks" },
    isAnonymous: false,
  },
  {
    projectName: "TaxTrackr",
    oneLiner: "A browser extension that helps people track local events",
    domain: "other",
    techStack: ["Python", "Selenium"],
    teamSize: "2-3",
    currentStage: "Almost complete",
    failureReason: "The professor's project requirements changed and this no longer counted for credit.",
    timeSpent: { value: 2, unit: "days" },
    isAnonymous: false,
  },
  {
    projectName: "ExamEcho",
    oneLiner: "A casual game prototype about surviving as a student",
    domain: "game",
    techStack: ["Unity", "C#"],
    teamSize: "4+",
    currentStage: "Prototype",
    failureReason: "The data we needed wasn't publicly available and scraping it was a legal gray area.",
    timeSpent: { value: 8, unit: "months" },
    isAnonymous: true,
  },
  {
    projectName: "DreamJournal",
    oneLiner: "A web dashboard that tracks commute routes for first-year students",
    domain: "web",
    techStack: ["React", "Node.js", "MongoDB"],
    teamSize: "solo",
    currentStage: "Almost complete",
    failureReason: "The professor's project requirements changed and this no longer counted for credit.",
    timeSpent: { value: 10, unit: "months" },
    isAnonymous: false,
  },
  {
    projectName: "FlashFact",
    oneLiner: "A bot that automatically organizes commute routes",
    domain: "other",
    techStack: ["Python", "Selenium"],
    teamSize: "2-3",
    currentStage: "Idea only",
    failureReason: "We built the whole backend before realizing nobody wanted the feature.",
    timeSpent: { value: 7, unit: "months" },
    isAnonymous: false,
  },
  {
    projectName: "CacheCraft",
    oneLiner: "A CLI tool that automates local events",
    domain: "other",
    techStack: ["Python", "Selenium"],
    teamSize: "solo",
    currentStage: "Almost complete",
    failureReason: "The API we depended on changed its pricing and broke our budget overnight.",
    timeSpent: { value: 6, unit: "months" },
    isAnonymous: false,
  },
  {
    projectName: "GitGraph",
    oneLiner: "An app that helps busy parents stay accountable to their goals",
    domain: "mobile",
    techStack: ["React Native", "Firebase"],
    teamSize: "2-3",
    currentStage: "Almost complete",
    failureReason: "Submitted it for a hackathon, didn't place, and interest died right after.",
    timeSpent: { value: 8, unit: "weeks" },
    isAnonymous: true,
  },
  {
    projectName: "GrammarGhost",
    oneLiner: "An IoT device that monitors commute routes in real time",
    domain: "hardware",
    techStack: ["ESP32", "MicroPython"],
    teamSize: "4+",
    currentStage: "Launched but abandoned",
    failureReason: "The professor's project requirements changed and this no longer counted for credit.",
    timeSpent: { value: 2, unit: "months" },
    isAnonymous: true,
  },
  {
    projectName: "PetSitter Pro",
    oneLiner: "A hardware prototype that senses conditions and alerts small teams",
    domain: "hardware",
    techStack: ["ESP32", "MicroPython"],
    teamSize: "4+",
    currentStage: "50% done",
    failureReason: "We realized a much better version of this already existed on the App Store.",
    timeSpent: { value: 3, unit: "weeks" },
    isAnonymous: true,
  },
  {
    projectName: "ShelfLife",
    oneLiner: "An IoT device that monitors spending habits in real time",
    domain: "hardware",
    techStack: ["ESP32", "MicroPython"],
    teamSize: "4+",
    currentStage: "Almost complete",
    failureReason: "Got distracted by a shinier idea two weeks in.",
    timeSpent: { value: 6, unit: "months" },
    isAnonymous: false,
  },
  {
    projectName: "StartupSim",
    oneLiner: "An IoT device that monitors study schedules in real time",
    domain: "hardware",
    techStack: ["ESP32", "MicroPython"],
    teamSize: "4+",
    currentStage: "Prototype",
    failureReason: "The professor's project requirements changed and this no longer counted for credit.",
    timeSpent: { value: 5, unit: "weeks" },
    isAnonymous: true,
  },
  {
    projectName: "SkillSwap",
    oneLiner: "A bot that automatically organizes job applications",
    domain: "other",
    techStack: ["Python", "Selenium"],
    teamSize: "4+",
    currentStage: "Launched but abandoned",
    failureReason: "Burned out after back-to-back all-nighters trying to hit a self-imposed deadline.",
    timeSpent: { value: 3, unit: "weeks" },
    isAnonymous: false,
  },
  {
    projectName: "ClusterCraft",
    oneLiner: "An IoT device that monitors class notes in real time",
    domain: "hardware",
    techStack: ["ESP32", "MicroPython"],
    teamSize: "solo",
    currentStage: "Prototype",
    failureReason: "The API we depended on changed its pricing and broke our budget overnight.",
    timeSpent: { value: 2, unit: "weeks" },
    isAnonymous: true,
  },
  {
    projectName: "StockSense",
    oneLiner: "A web app that turns spending habits into a clean weekly report",
    domain: "web",
    techStack: ["React", "Node.js", "MongoDB"],
    teamSize: "solo",
    currentStage: "Almost complete",
    failureReason: "Time zone differences made it impossible to collaborate consistently.",
    timeSpent: { value: 3, unit: "weeks" },
    isAnonymous: true,
  },
  {
    projectName: "CodeCrumb",
    oneLiner: "A browser extension that helps people track sleep patterns",
    domain: "other",
    techStack: ["WordPress", "PHP"],
    teamSize: "4+",
    currentStage: "Launched but abandoned",
    failureReason: "Team lost motivation once the semester's exams started piling up.",
    timeSpent: { value: 4, unit: "weeks" },
    isAnonymous: false,
  },
  {
    projectName: "GhostWriter AI",
    oneLiner: "A DIY gadget that automates job applications",
    domain: "hardware",
    techStack: ["Raspberry Pi", "Python"],
    teamSize: "solo",
    currentStage: "Prototype",
    failureReason: "We built the whole backend before realizing nobody wanted the feature.",
    timeSpent: { value: 3, unit: "days" },
    isAnonymous: false,
  },
  {
    projectName: "CivicPulse",
    oneLiner: "An app that helps busy parents stay accountable to their goals",
    domain: "mobile",
    techStack: ["Flutter", "Firebase"],
    teamSize: "2-3",
    currentStage: "Idea only",
    failureReason: "The data we needed wasn't publicly available and scraping it was a legal gray area.",
    timeSpent: { value: 7, unit: "days" },
    isAnonymous: false,
  },
  {
    projectName: "ExpenseEcho",
    oneLiner: "A platform that helps hostel roommates compare prices in real time",
    domain: "web",
    techStack: ["React", "Node.js", "MongoDB"],
    teamSize: "solo",
    currentStage: "Launched but abandoned",
    failureReason: "The hosting bill got too expensive to justify for a side project.",
    timeSpent: { value: 8, unit: "weeks" },
    isAnonymous: false,
  },
  {
    projectName: "QueryQuick",
    oneLiner: "A hardware prototype that senses conditions and alerts first-year students",
    domain: "hardware",
    techStack: ["Raspberry Pi", "Python"],
    teamSize: "solo",
    currentStage: "Idea only",
    failureReason: "Deployment kept failing and none of us knew enough DevOps to fix it in time.",
    timeSpent: { value: 6, unit: "weeks" },
    isAnonymous: false,
  },
  {
    projectName: "BugBounty Board",
    oneLiner: "A CLI tool that automates sleep patterns",
    domain: "other",
    techStack: ["Python", "Selenium"],
    teamSize: "2-3",
    currentStage: "Prototype",
    failureReason: "Deployment kept failing and none of us knew enough DevOps to fix it in time.",
    timeSpent: { value: 8, unit: "months" },
    isAnonymous: false,
  },
  {
    projectName: "ThriftFinder",
    oneLiner: "An AI assistant that turns class notes into a color-coded calendar",
    domain: "ml",
    techStack: ["Python", "PyTorch", "FastAPI"],
    teamSize: "4+",
    currentStage: "Almost complete",
    failureReason: "Got busy with internship interviews and never found time to come back to it.",
    timeSpent: { value: 4, unit: "weeks" },
    isAnonymous: false,
  },
  {
    projectName: "PayrollPal",
    oneLiner: "An AI assistant that turns class notes into an actionable summary",
    domain: "ml",
    techStack: ["Python", "Stable Diffusion", "FastAPI"],
    teamSize: "solo",
    currentStage: "Almost complete",
    failureReason: "Submitted it for a hackathon, didn't place, and interest died right after.",
    timeSpent: { value: 5, unit: "weeks" },
    isAnonymous: false,
  },
  {
    projectName: "LogLens",
    oneLiner: "A web dashboard that tracks study schedules for freelancers",
    domain: "web",
    techStack: ["Next.js", "Supabase", "TypeScript"],
    teamSize: "4+",
    currentStage: "Launched but abandoned",
    failureReason: "The scope kept growing until it felt impossible to ship anything.",
    timeSpent: { value: 10, unit: "months" },
    isAnonymous: false,
  },
  {
    projectName: "QueueBuster",
    oneLiner: "A browser game built to teach first-year students about study schedules",
    domain: "game",
    techStack: ["Unity", "C#"],
    teamSize: "2-3",
    currentStage: "Idea only",
    failureReason: "The hosting bill got too expensive to justify for a side project.",
    timeSpent: { value: 9, unit: "months" },
    isAnonymous: false,
  },
  {
    projectName: "SleepScribe",
    oneLiner: "An app that helps hostel roommates find study partners nearby",
    domain: "mobile",
    techStack: ["Flutter", "Firebase"],
    teamSize: "4+",
    currentStage: "Almost complete",
    failureReason: "Pivoted the idea three times and lost all momentum in the process.",
    timeSpent: { value: 10, unit: "weeks" },
    isAnonymous: true,
  },
  {
    projectName: "PairUp",
    oneLiner: "A browser-based tool that helps hostel roommates manage their time better",
    domain: "web",
    techStack: ["Vue.js", "Django", "PostgreSQL"],
    teamSize: "solo",
    currentStage: "Almost complete",
    failureReason: "The API we depended on changed its pricing and broke our budget overnight.",
    timeSpent: { value: 1, unit: "months" },
    isAnonymous: false,
  },
  {
    projectName: "FocusFort",
    oneLiner: "A mobile-first tool that turns class notes into a color-coded calendar",
    domain: "mobile",
    techStack: ["Flutter", "Firebase"],
    teamSize: "4+",
    currentStage: "Idea only",
    failureReason: "The data we needed wasn't publicly available and scraping it was a legal gray area.",
    timeSpent: { value: 5, unit: "weeks" },
    isAnonymous: false,
  },
  {
    projectName: "RentWise",
    oneLiner: "A web app that turns study schedules into an actionable summary",
    domain: "web",
    techStack: ["Angular", "Spring Boot", "MySQL"],
    teamSize: "4+",
    currentStage: "50% done",
    failureReason: "The data we needed wasn't publicly available and scraping it was a legal gray area.",
    timeSpent: { value: 10, unit: "weeks" },
    isAnonymous: false,
  },
  {
    projectName: "DataDock",
    oneLiner: "A hardware prototype that senses conditions and alerts first-year students",
    domain: "hardware",
    techStack: ["Arduino", "C++", "Raspberry Pi"],
    teamSize: "2-3",
    currentStage: "Almost complete",
    failureReason: "Time zone differences made it impossible to collaborate consistently.",
    timeSpent: { value: 8, unit: "days" },
    isAnonymous: false,
  },
  {
    projectName: "MeetingMuse",
    oneLiner: "An app that helps freelancers stay accountable to their goals",
    domain: "mobile",
    techStack: ["React Native", "Firebase"],
    teamSize: "2-3",
    currentStage: "50% done",
    failureReason: "The data we needed wasn't publicly available and scraping it was a legal gray area.",
    timeSpent: { value: 3, unit: "days" },
    isAnonymous: false,
  },
  {
    projectName: "InvestIQ",
    oneLiner: "A mobile app that helps busy parents split bills fairly",
    domain: "mobile",
    techStack: ["Flutter", "Firebase", "HealthKit"],
    teamSize: "solo",
    currentStage: "Prototype",
    failureReason: "The hosting bill got too expensive to justify for a side project.",
    timeSpent: { value: 10, unit: "weeks" },
    isAnonymous: true,
  },
  {
    projectName: "AlumniLink",
    oneLiner: "An ML-powered tool that predicts local events for small teams",
    domain: "ml",
    techStack: ["Python", "OpenAI API", "React"],
    teamSize: "4+",
    currentStage: "Idea only",
    failureReason: "Got distracted by a shinier idea two weeks in.",
    timeSpent: { value: 10, unit: "days" },
    isAnonymous: false,
  },
  {
    projectName: "ServerSitter",
    oneLiner: "A hardware prototype that senses conditions and alerts small teams",
    domain: "hardware",
    techStack: ["Raspberry Pi", "Python"],
    teamSize: "4+",
    currentStage: "50% done",
    failureReason: "Time zone differences made it impossible to collaborate consistently.",
    timeSpent: { value: 2, unit: "days" },
    isAnonymous: false,
  },
  {
    projectName: "SolarScout",
    oneLiner: "A casual game prototype about surviving as a roommate",
    domain: "game",
    techStack: ["Phaser.js", "JavaScript"],
    teamSize: "solo",
    currentStage: "Almost complete",
    failureReason: "We spent too long designing the perfect logo and never wrote the first line of code.",
    timeSpent: { value: 3, unit: "months" },
    isAnonymous: false,
  },
  {
    projectName: "PitchDeckAI",
    oneLiner: "A mobile-first tool that turns sleep patterns into an actionable summary",
    domain: "mobile",
    techStack: ["Flutter", "Firebase", "HealthKit"],
    teamSize: "solo",
    currentStage: "Launched but abandoned",
    failureReason: "Pivoted the idea three times and lost all momentum in the process.",
    timeSpent: { value: 8, unit: "months" },
    isAnonymous: false,
  },
  {
    projectName: "NoteNest",
    oneLiner: "A browser game built to teach first-year students about job applications",
    domain: "game",
    techStack: ["Unity", "C#"],
    teamSize: "2-3",
    currentStage: "Prototype",
    failureReason: "Time zone differences made it impossible to collaborate consistently.",
    timeSpent: { value: 1, unit: "days" },
    isAnonymous: false,
  },
  {
    projectName: "LatencyLog",
    oneLiner: "A CLI tool that automates grocery lists",
    domain: "other",
    techStack: ["Node.js", "Puppeteer"],
    teamSize: "4+",
    currentStage: "Almost complete",
    failureReason: "We argued about the tech stack for two weeks and never actually started building.",
    timeSpent: { value: 4, unit: "months" },
    isAnonymous: false,
  },
  {
    projectName: "MockMaker",
    oneLiner: "An AI tool that flags anomalies in class notes",
    domain: "ml",
    techStack: ["Python", "OpenAI API", "React"],
    teamSize: "2-3",
    currentStage: "Launched but abandoned",
    failureReason: "The hosting bill got too expensive to justify for a side project.",
    timeSpent: { value: 2, unit: "days" },
    isAnonymous: false,
  },
  {
    projectName: "FitFam",
    oneLiner: "A hardware prototype that senses conditions and alerts freelancers",
    domain: "hardware",
    techStack: ["Raspberry Pi", "Python"],
    teamSize: "2-3",
    currentStage: "Almost complete",
    failureReason: "Got busy with internship interviews and never found time to come back to it.",
    timeSpent: { value: 7, unit: "weeks" },
    isAnonymous: false,
  },
  {
    projectName: "CarpoolConnect",
    oneLiner: "An ML-powered tool that predicts class notes for busy parents",
    domain: "ml",
    techStack: ["Python", "PyTorch", "FastAPI"],
    teamSize: "solo",
    currentStage: "Launched but abandoned",
    failureReason: "Turns out none of us actually wanted to use it ourselves.",
    timeSpent: { value: 10, unit: "months" },
    isAnonymous: false,
  },
  {
    projectName: "TestTube CI",
    oneLiner: "An IoT device that monitors sleep patterns in real time",
    domain: "hardware",
    techStack: ["Raspberry Pi", "Python"],
    teamSize: "solo",
    currentStage: "Prototype",
    failureReason: "Team lost motivation once the semester's exams started piling up.",
    timeSpent: { value: 7, unit: "weeks" },
    isAnonymous: false,
  },
  {
    projectName: "FreelanceFlow",
    oneLiner: "An IoT device that monitors study schedules in real time",
    domain: "hardware",
    techStack: ["Arduino", "C++", "Raspberry Pi"],
    teamSize: "2-3",
    currentStage: "Prototype",
    failureReason: "The data we needed wasn't publicly available and scraping it was a legal gray area.",
    timeSpent: { value: 8, unit: "months" },
    isAnonymous: true,
  },
  {
    projectName: "LaundryLoop",
    oneLiner: "A DIY gadget that automates study schedules",
    domain: "hardware",
    techStack: ["Arduino", "C++", "Raspberry Pi"],
    teamSize: "4+",
    currentStage: "Prototype",
    failureReason: "The professor's project requirements changed and this no longer counted for credit.",
    timeSpent: { value: 4, unit: "months" },
    isAnonymous: false,
  },
  {
    projectName: "ShiftSwap",
    oneLiner: "A small game where players compete to manage grocery lists",
    domain: "game",
    techStack: ["Unreal Engine", "C++"],
    teamSize: "4+",
    currentStage: "Prototype",
    failureReason: "The API we depended on changed its pricing and broke our budget overnight.",
    timeSpent: { value: 8, unit: "days" },
    isAnonymous: false,
  },
  {
    projectName: "StandupBot",
    oneLiner: "A CLI tool that automates class notes",
    domain: "other",
    techStack: ["Node.js", "Puppeteer"],
    teamSize: "2-3",
    currentStage: "50% done",
    failureReason: "We built the whole backend before realizing nobody wanted the feature.",
    timeSpent: { value: 6, unit: "weeks" },
    isAnonymous: true,
  },
  {
    projectName: "ApiArtisan",
    oneLiner: "A web app that turns local events into a simple shareable link",
    domain: "web",
    techStack: ["Vue.js", "Django", "PostgreSQL"],
    teamSize: "4+",
    currentStage: "Launched but abandoned",
    failureReason: "Team lost motivation once the semester's exams started piling up.",
    timeSpent: { value: 5, unit: "days" },
    isAnonymous: true,
  },
  {
    projectName: "SchemaSmith",
    oneLiner: "A web app that turns commute routes into a clean weekly report",
    domain: "web",
    techStack: ["React", "GraphQL", "PostgreSQL"],
    teamSize: "4+",
    currentStage: "50% done",
    failureReason: "Burned out after back-to-back all-nighters trying to hit a self-imposed deadline.",
    timeSpent: { value: 10, unit: "days" },
    isAnonymous: false,
  },
  {
    projectName: "SprintSense",
    oneLiner: "A mobile-first tool that turns class notes into a simple shareable link",
    domain: "mobile",
    techStack: ["React Native", "Node.js", "MongoDB"],
    teamSize: "solo",
    currentStage: "50% done",
    failureReason: "We realized a much better version of this already existed on the App Store.",
    timeSpent: { value: 3, unit: "months" },
    isAnonymous: false,
  },
  {
    projectName: "RecipeRemix",
    oneLiner: "A DIY gadget that automates local events",
    domain: "hardware",
    techStack: ["ESP32", "MicroPython"],
    teamSize: "solo",
    currentStage: "Idea only",
    failureReason: "We built the whole backend before realizing nobody wanted the feature.",
    timeSpent: { value: 9, unit: "months" },
    isAnonymous: false,
  },
  {
    projectName: "CodeReviewr",
    oneLiner: "A small game where players compete to manage class notes",
    domain: "game",
    techStack: ["Unreal Engine", "C++"],
    teamSize: "solo",
    currentStage: "Prototype",
    failureReason: "Submitted it for a hackathon, didn't place, and interest died right after.",
    timeSpent: { value: 10, unit: "months" },
    isAnonymous: false,
  },
  {
    projectName: "WaterWise",
    oneLiner: "A bot that automatically organizes class notes",
    domain: "other",
    techStack: ["WordPress", "PHP"],
    teamSize: "4+",
    currentStage: "Idea only",
    failureReason: "Burned out after back-to-back all-nighters trying to hit a self-imposed deadline.",
    timeSpent: { value: 4, unit: "weeks" },
    isAnonymous: true,
  },
  {
    projectName: "PitchPerfect",
    oneLiner: "A browser extension that helps people track class notes",
    domain: "other",
    techStack: ["Python", "Selenium"],
    teamSize: "solo",
    currentStage: "Almost complete",
    failureReason: "We realized a much better version of this already existed on the App Store.",
    timeSpent: { value: 5, unit: "days" },
    isAnonymous: false,
  },
  {
    projectName: "LostAndFound Hub",
    oneLiner: "A mobile app that helps small teams split bills fairly",
    domain: "mobile",
    techStack: ["Flutter", "Firebase", "HealthKit"],
    teamSize: "solo",
    currentStage: "Prototype",
    failureReason: "Submitted it for a hackathon, didn't place, and interest died right after.",
    timeSpent: { value: 3, unit: "weeks" },
    isAnonymous: false,
  },
  {
    projectName: "ScholarSearch",
    oneLiner: "A hardware prototype that senses conditions and alerts remote workers",
    domain: "hardware",
    techStack: ["Raspberry Pi", "Python"],
    teamSize: "4+",
    currentStage: "Prototype",
    failureReason: "One teammate ghosted after week two and the rest of us couldn't keep pace.",
    timeSpent: { value: 5, unit: "months" },
    isAnonymous: false,
  },
  {
    projectName: "LangLoop",
    oneLiner: "A browser extension that helps people track grocery lists",
    domain: "other",
    techStack: ["WordPress", "PHP"],
    teamSize: "2-3",
    currentStage: "Prototype",
    failureReason: "Got busy with internship interviews and never found time to come back to it.",
    timeSpent: { value: 5, unit: "months" },
    isAnonymous: false,
  },
  {
    projectName: "ParkSpot",
    oneLiner: "A web app that turns commute routes into an actionable summary",
    domain: "web",
    techStack: ["React", "Node.js", "MongoDB"],
    teamSize: "solo",
    currentStage: "Idea only",
    failureReason: "The core feature turned out to be way harder to build than we scoped.",
    timeSpent: { value: 1, unit: "days" },
    isAnonymous: false,
  },
  {
    projectName: "VoiceVault",
    oneLiner: "A bot that automatically organizes grocery lists",
    domain: "other",
    techStack: ["Python", "Selenium"],
    teamSize: "4+",
    currentStage: "Idea only",
    failureReason: "The scope kept growing until it felt impossible to ship anything.",
    timeSpent: { value: 2, unit: "months" },
    isAnonymous: true,
  },
  {
    projectName: "AlertAnchor",
    oneLiner: "A mobile-first tool that turns class notes into a clean weekly report",
    domain: "mobile",
    techStack: ["Flutter", "Firebase", "HealthKit"],
    teamSize: "4+",
    currentStage: "Launched but abandoned",
    failureReason: "Time zone differences made it impossible to collaborate consistently.",
    timeSpent: { value: 9, unit: "days" },
    isAnonymous: false,
  },
  {
    projectName: "ByteBudget",
    oneLiner: "A web dashboard that tracks local events for hostel roommates",
    domain: "web",
    techStack: ["Vue.js", "Django", "PostgreSQL"],
    teamSize: "2-3",
    currentStage: "Almost complete",
    failureReason: "We spent too long designing the perfect logo and never wrote the first line of code.",
    timeSpent: { value: 2, unit: "days" },
    isAnonymous: false,
  },
  {
    projectName: "CryptoCompass",
    oneLiner: "An ML-powered tool that predicts grocery lists for freelancers",
    domain: "ml",
    techStack: ["Python", "OpenAI API", "React"],
    teamSize: "4+",
    currentStage: "Idea only",
    failureReason: "Team lost motivation once the semester's exams started piling up.",
    timeSpent: { value: 5, unit: "months" },
    isAnonymous: false,
  },
  {
    projectName: "InternHunt",
    oneLiner: "A web dashboard that tracks grocery lists for solo travelers",
    domain: "web",
    techStack: ["Vue.js", "Django", "PostgreSQL"],
    teamSize: "4+",
    currentStage: "Prototype",
    failureReason: "The hosting bill got too expensive to justify for a side project.",
    timeSpent: { value: 3, unit: "days" },
    isAnonymous: false,
  },
  {
    projectName: "EdgeEcho",
    oneLiner: "A browser extension that helps people track sleep patterns",
    domain: "other",
    techStack: ["Python", "Selenium"],
    teamSize: "solo",
    currentStage: "Almost complete",
    failureReason: "Turns out none of us actually wanted to use it ourselves.",
    timeSpent: { value: 6, unit: "weeks" },
    isAnonymous: false,
  },
  {
    projectName: "LibroLink",
    oneLiner: "An AI assistant that turns study schedules into an actionable summary",
    domain: "ml",
    techStack: ["Python", "OpenAI API", "React"],
    teamSize: "2-3",
    currentStage: "Launched but abandoned",
    failureReason: "Team lost motivation once the semester's exams started piling up.",
    timeSpent: { value: 4, unit: "days" },
    isAnonymous: false,
  },
  {
    projectName: "GymBuddy",
    oneLiner: "A browser game built to teach first-year students about sleep patterns",
    domain: "game",
    techStack: ["Phaser.js", "JavaScript"],
    teamSize: "2-3",
    currentStage: "Launched but abandoned",
    failureReason: "Got distracted by a shinier idea two weeks in.",
    timeSpent: { value: 9, unit: "days" },
    isAnonymous: false,
  },
  {
    projectName: "CalmCorner",
    oneLiner: "A browser extension that helps people track grocery lists",
    domain: "other",
    techStack: ["WordPress", "PHP"],
    teamSize: "2-3",
    currentStage: "Idea only",
    failureReason: "We built the whole backend before realizing nobody wanted the feature.",
    timeSpent: { value: 5, unit: "weeks" },
    isAnonymous: false,
  },
  {
    projectName: "TaskTide",
    oneLiner: "An ML-powered tool that predicts sleep patterns for hostel roommates",
    domain: "ml",
    techStack: ["Python", "scikit-learn", "FastAPI"],
    teamSize: "4+",
    currentStage: "Idea only",
    failureReason: "The API we depended on changed its pricing and broke our budget overnight.",
    timeSpent: { value: 4, unit: "days" },
    isAnonymous: true,
  },
  {
    projectName: "StepStreak",
    oneLiner: "A web dashboard that tracks study schedules for solo travelers",
    domain: "web",
    techStack: ["Angular", "Spring Boot", "MySQL"],
    teamSize: "4+",
    currentStage: "50% done",
    failureReason: "Time zone differences made it impossible to collaborate consistently.",
    timeSpent: { value: 5, unit: "weeks" },
    isAnonymous: false,
  },
  {
    projectName: "BudgetBloom",
    oneLiner: "An ML-powered tool that predicts job applications for busy parents",
    domain: "ml",
    techStack: ["Python", "scikit-learn", "FastAPI"],
    teamSize: "solo",
    currentStage: "Prototype",
    failureReason: "The hosting bill got too expensive to justify for a side project.",
    timeSpent: { value: 9, unit: "days" },
    isAnonymous: false,
  },
  {
    projectName: "CampusCompass",
    oneLiner: "An app that helps remote workers find study partners nearby",
    domain: "mobile",
    techStack: ["Kotlin", "Firebase"],
    teamSize: "4+",
    currentStage: "Idea only",
    failureReason: "The API we depended on changed its pricing and broke our budget overnight.",
    timeSpent: { value: 7, unit: "months" },
    isAnonymous: false,
  },
  {
    projectName: "MoodMap",
    oneLiner: "A platform that helps remote workers compare prices in real time",
    domain: "web",
    techStack: ["React", "Node.js", "MongoDB"],
    teamSize: "2-3",
    currentStage: "Idea only",
    failureReason: "Deployment kept failing and none of us knew enough DevOps to fix it in time.",
    timeSpent: { value: 7, unit: "months" },
    isAnonymous: false,
  },
  {
    projectName: "MealMate",
    oneLiner: "An app that helps hostel roommates stay accountable to their goals",
    domain: "mobile",
    techStack: ["Kotlin", "Firebase"],
    teamSize: "2-3",
    currentStage: "Prototype",
    failureReason: "We built the whole backend before realizing nobody wanted the feature.",
    timeSpent: { value: 1, unit: "months" },
    isAnonymous: false,
  },
  {
    projectName: "ClientPing",
    oneLiner: "A hardware prototype that senses conditions and alerts first-year students",
    domain: "hardware",
    techStack: ["Arduino", "C++", "Raspberry Pi"],
    teamSize: "4+",
    currentStage: "Prototype",
    failureReason: "Team lost motivation once the semester's exams started piling up.",
    timeSpent: { value: 5, unit: "weeks" },
    isAnonymous: false,
  },];

const seedDB = async () => {
  try {
    await mongoose.connect(process.env.MONGO_URI);
    console.log("✅ MongoDB Connected");

    await Draft.deleteMany({});
    console.log("🗑️  Cleared existing burials");

    await Draft.insertMany(fakeBurials);
    console.log(`🌱 Seeded ${fakeBurials.length} fake burials`);

    mongoose.connection.close();
    console.log("🔌 Connection closed");
  } catch (err) {
    console.error("❌ Seed error:", err);
    process.exit(1);
  }
};

seedDB();
