/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkspaceRouteImport } from './routes/workspace'
import { Route as StackIntelligenceRouteImport } from './routes/stack-intelligence'
import { Route as RevivalBoardRouteImport } from './routes/revival-board'
import { Route as InsightsLabRouteImport } from './routes/insights-lab'
import { Route as IdeaReviewRouteImport } from './routes/idea-review'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectSlugRouteImport } from './routes/project.$slug'

const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const StackIntelligenceRoute = StackIntelligenceRouteImport.update({
  id: '/stack-intelligence',
  path: '/stack-intelligence',
  getParentRoute: () => rootRouteImport,
} as any)
const RevivalBoardRoute = RevivalBoardRouteImport.update({
  id: '/revival-board',
  path: '/revival-board',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsLabRoute = InsightsLabRouteImport.update({
  id: '/insights-lab',
  path: '/insights-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const IdeaReviewRoute = IdeaReviewRouteImport.update({
  id: '/idea-review',
  path: '/idea-review',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectSlugRoute = ProjectSlugRouteImport.update({
  id: '/project/$slug',
  path: '/project/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/feed': typeof FeedRoute
  '/idea-review': typeof IdeaReviewRoute
  '/insights-lab': typeof InsightsLabRoute
  '/revival-board': typeof RevivalBoardRoute
  '/stack-intelligence': typeof StackIntelligenceRoute
  '/workspace': typeof WorkspaceRoute
  '/project/$slug': typeof ProjectSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/feed': typeof FeedRoute
  '/idea-review': typeof IdeaReviewRoute
  '/insights-lab': typeof InsightsLabRoute
  '/revival-board': typeof RevivalBoardRoute
  '/stack-intelligence': typeof StackIntelligenceRoute
  '/workspace': typeof WorkspaceRoute
  '/project/$slug': typeof ProjectSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/feed': typeof FeedRoute
  '/idea-review': typeof IdeaReviewRoute
  '/insights-lab': typeof InsightsLabRoute
  '/revival-board': typeof RevivalBoardRoute
  '/stack-intelligence': typeof StackIntelligenceRoute
  '/workspace': typeof WorkspaceRoute
  '/project/$slug': typeof ProjectSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/feed'
    | '/idea-review'
    | '/insights-lab'
    | '/revival-board'
    | '/stack-intelligence'
    | '/workspace'
    | '/project/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/feed'
    | '/idea-review'
    | '/insights-lab'
    | '/revival-board'
    | '/stack-intelligence'
    | '/workspace'
    | '/project/$slug'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/feed'
    | '/idea-review'
    | '/insights-lab'
    | '/revival-board'
    | '/stack-intelligence'
    | '/workspace'
    | '/project/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  FeedRoute: typeof FeedRoute
  IdeaReviewRoute: typeof IdeaReviewRoute
  InsightsLabRoute: typeof InsightsLabRoute
  RevivalBoardRoute: typeof RevivalBoardRoute
  StackIntelligenceRoute: typeof StackIntelligenceRoute
  WorkspaceRoute: typeof WorkspaceRoute
  ProjectSlugRoute: typeof ProjectSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workspace': {
      id: '/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stack-intelligence': {
      id: '/stack-intelligence'
      path: '/stack-intelligence'
      fullPath: '/stack-intelligence'
      preLoaderRoute: typeof StackIntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/revival-board': {
      id: '/revival-board'
      path: '/revival-board'
      fullPath: '/revival-board'
      preLoaderRoute: typeof RevivalBoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights-lab': {
      id: '/insights-lab'
      path: '/insights-lab'
      fullPath: '/insights-lab'
      preLoaderRoute: typeof InsightsLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/idea-review': {
      id: '/idea-review'
      path: '/idea-review'
      fullPath: '/idea-review'
      preLoaderRoute: typeof IdeaReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/$slug': {
      id: '/project/$slug'
      path: '/project/$slug'
      fullPath: '/project/$slug'
      preLoaderRoute: typeof ProjectSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  FeedRoute: FeedRoute,
  IdeaReviewRoute: IdeaReviewRoute,
  InsightsLabRoute: InsightsLabRoute,
  RevivalBoardRoute: RevivalBoardRoute,
  StackIntelligenceRoute: StackIntelligenceRoute,
  WorkspaceRoute: WorkspaceRoute,
  ProjectSlugRoute: ProjectSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
